--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/fuyutsuki/Texter
branches:
  - master
projects:
 RulesUI:
    path: ""
    icon: ""
    libs:
      - DG-RulesUI-5.phar
        version: 1.3.0
...
