name: DG-Regeln

main: GodzHard\RulesUI\Main

api: 3.11.1

version: 1.0

author: GodzHard-Fixed From DragonfireHD98

commands:

  rulesui:

    description: §6§lÖffnet die §cRegeln 

    aliases:

      - rules

      - info

